### ISSUE TITLE
GPML2MD for Jekyll

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-development#1]

**Comment by ariutta** [comment]
This page lists static site generators:
https://jamstack.org/generators/

Two Java examples:
- https://orchid.run/
- https://jbake.org/

**Comment by ariutta** [comment]
GH Actions to create GH Pages:
- https://github.com/marketplace/actions/github-pages
- https://github.com/marketplace/actions/release-github-pages
- https://github.com/marketplace/actions/vuepress-to-github-pages

**Comment by AlexanderPico** [comment]
Goal MD for WP554: https://raw.githubusercontent.com/wikipathways/wikipathways.github.io/main/_pathways/WP554.md

**Comment by AlexanderPico** [comment]
Let's use Python (decision in 7/19 meeting)

**Comment by ariutta** [comment]
The [create_pathway_frontmatter.py script](https://github.com/wikipathways/wikipathways-database/blob/main/scripts/create_pathway_frontmatter.py) and the [create_pathway_frontmatter.yml GH Action](https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/create_pathway_frontmatter.yml) partially address the current issue.

*Items remaining:*
- [x] Format dates not as a string in YAML (see [this line](https://github.com/wikipathways/wikipathways-database/blob/main/scripts/create_pathway_frontmatter.py#L36))
- [x] Detect the file that changed ([this line](https://github.com/wikipathways/wikipathways-database/blob/main/scripts/create_pathway_frontmatter.py#L13))
- [ ] Fill in [missing fields](https://github.com/wikipathways/wikipathways-database/blob/main/scripts/create_pathway_frontmatter.py#L48): `title`, `communities`, `github-authors`.
   - Should `title` be in the `.info` file, or should we be reading in from the GPML?
   - Are the files in the [`./communities`](https://github.com/wikipathways/wikipathways-database/tree/main/communities) directory the single-source of truth for `communities`? *Answer: Yes*
      - What happens if someone manually changes the communities field in [./pathways/WP554.md](https://github.com/wikipathways/wikipathways-database/blob/main/pathways/WP554/WP554.md?plain=1#L23) but doesn't change the corresponding file(s) in the `./communities` directory? *Answer: This would be incorrect. Don't handle it.*
      - Should a change to a file in the `./communities` directory regarding WP554 trigger a GH Action that updates ./pathways/WP554.md? *Answer: Yes, the .md frontmatter file should be updated.*
   - Do we have mappings from `authors` to `github-authors`?

**Comment by AlexanderPico** [comment]
More details on ideal annotation processing. If you recall, we had to dramatically prune the list of annotation pages on the Jekyll site. We settled on these top-level parent terms for each ontology: https://new.wikipathways.org/browse/annotations.html (click on each to get their IDs). For ontology based buttons to be useful on the site, however, we need to map from the provided identifiers to one or more of these parent terms. Fortunately, the cached ontology CSV files have this information (e.g., https://raw.githubusercontent.com/wikipathways/wikipathways-database/main/annotations/PW.csv). A recursive search of "Parents" should hit on one or more of the selected top-level terms.

So, currently you take a PW ID from .info and translate that into something like:
```
- type: Pathway Ontology
  value: inflammatory response pathway
```
I think what we want is something like this:
```
- type: Pathway Ontology
  value: inflammatory response pathway
  parent: signaling pathway
```
Where "parent" isn't necessarily the immediate parent of the provided term, but is the eventual parent in a recursive search. The recursion should not go more then ~7 steps (2-3 will be common). If more than 7, you can simply skip and leave it blank.

This is not critical to Milestone 1, but would be necessary for the annotation buttons to work on the site.

**Comment by ariutta** [comment]
Can we keep a list of the parent terms somewhere in the `annotations` directory?

**Comment by AlexanderPico** [comment]
@ariutta  Sure! https://github.com/wikipathways/wikipathways-database/blob/main/annotations/top_parent_terms.tsv
Feel free to restructure the list however it's most useful. It should rarely change and it would be done manually in coordination with editing  annotation .md files in the Jekyll site.

**Comment by ariutta** [comment]
It appears current list of parents for diseases doesn't include a parent for hypertension `DOID:10763`. Do we want to add an entry like cardiovascular system disease `DOID:1287` or just not have a parent for hypertension?

**Comment by ariutta** [comment]
Other than the issue with hypertension not having a parent, the current code should now be handling it close to correctly.

**Comment by Chris-Evelo** [comment]
I think we should not be the ones deciding whether hypertension has a parent or not. We should get the ontology tree from the ontology itself. Is that not what we do? (The direct parent is "artery disease DOID:10763" according to: https://disease-ontology.org/)

**Comment by ariutta** [comment]
Yes, we're getting the parent from the ontology file. The issue is just whether to expand our list of tags in this file: https://new.wikipathways.org/browse/annotations.html

I'll take a look at the stats for how many are null.

**Comment by ariutta** [comment]
I identified the three parents not already [here](https://new.wikipathways.org/browse/annotations.html) that have the largest number of pathways:
1. cardiovascular system disease (DOID:1287) has 43
2. central nervous system disease (DOID:331) has 36
3. gonadal disease (DOID:2277) has 11

I propose we add DOID:1287 and DOID:331.

**Comment by AlexanderPico** [comment]
Go for it! Just add md files for the top-level terms you want here: https://github.com/wikipathways/wikipathways.github.io/tree/main/_annotations
