### ISSUE TITLE
How to handle authors?

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-development#13]
We have a deep history of author usernames, real names and emails from WP. Going forward to have GitHub users.

How to connect authors with GitHub accounts? How to write history?

**Comment by ariutta** [comment]
Related:
https://github.com/wikipathways/wikipathways-database/blob/0df9006d360f4234b2e5bc0c810f6bb8ae1bdf4c/scripts/create_pathway_frontmatter.py#L168

**Comment by AlexanderPico** [comment]
https://github.com/wikipathways/wikipathways-database/blob/main/scripts/author_list.csv
