### ISSUE TITLE
Demo GitHub Pages site

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-development#5]
Built from GPML2MD content and maybe using the toolforge widget or SVG images directly.

This would be a very simple, read-only view of the content. 

Could it replace the need to maintain a Mediawiki instance?

**Comment by AlexanderPico** [comment]
Here's a repo hosting a jekyll site via GitHub pages that gives a quite a bit of flexibility:
https://github.com/wikipathways/wikipathways.github.io

View the site at: https://wikipathways.github.io/

**Comment by AlexanderPico** [comment]
If we want any tables in our website pathway pages using Jekyll, then we might try generating CSV files as part of the set of conversions we are planning as part of curation/PR merging. These CSV files would be useful as downloadable content for users, but they can also be directly used to generate HTML table with a little bit of template markdown. See https://jekyllrb.com/docs/datafiles/.

Likewise, we can generate JSON and TSV as well to give users some options. Jekyll can work with any of these as datafiles.

Example tables:

- Participants (a.k.a DataNodes), including states, comments and other annotations. 
- Relationships (a.k.a Annotated Interactions), if annotated. 

Each table can offer download options and links to RDF, Wikidata, web service and R queries (with caveat about timed releases?)

**Comment by AlexanderPico** [comment]
Features we want for the image:

- interactive viewer using updated pvjson/svg that has to be converted at time of curation/PR merge
- download options for svg, png

We also want some general linkouts and options:

- Edit in PathVisio (link to instructions?)
- Open in Cytoscape (if open/installed)
- Link to NDEx (if there)
- Link to Scholia (if there)

**Comment by mkutmon** [comment]
Great work!
Some comments to different parts discussed before:
- .csv files should be easy to create and the ones needed for the pathway page itself could be in the pathway folder.
- Edit in PathVisio - for now link to instructions - in the future link to open pathvisio (working on the installers) - so similar to "Open in Cytoscape"

**Comment by mkutmon** [comment]
For the tables - can we use sort/filter? can we show change how many are shown (with a next page button)?

**Comment by AlexanderPico** [comment]
> For the tables - can we use sort/filter? can we show change how many are shown (with a next page button)?

Sure. In the end it's HTML/JS, so we can do whatever we want. In most cases, we'll likely want to stick with simple markdown, but for tables in particular, it is common to switch to HTML anyways since markdown sucks for tables :) So, we're already crossing the "simplicity line" and can as deep as we want.

**Comment by AlexanderPico** [comment]
Let's try a facetted browse interface using Jekyll. It might not be too difficult...

**Comment by AlexanderPico** [comment]
Mock-ups: https://docs.google.com/presentation/d/1YfnKLf0YbNToLho9l_mLpKC8iYDBPY-Gv7o0vjDxisI/edit#slide=id.ge29142f938_0_25

**Comment by AlexanderPico** [comment]
https://wikipathways.github.io/pathways/WP554.html

Latest updates include:

- Pure templated content for pathway pages
- Social media share buttons
- Authors
- Participants read from csv data table
- Reference links generated from PMIDs

**Comment by AlexanderPico** [comment]
@mkutmon Here is the latest example of what the .md file would need to look like to generate the current pages so far:
https://raw.githubusercontent.com/wikipathways/wikipathways.github.io/main/_pathways/WP554.md

In addition, we'd want CSV files for the Participants, Interactions and References tables.  The first two are probably generally useful and users may want to download them anyways. The one for References is needed to centralize the PubMed web service call we'll need to make to get the citation text per PMID. I figure once per merged edit is better than once per page view :D

Example data files that we could ideally generate from GPML are here:
https://github.com/wikipathways/wikipathways.github.io/tree/main/_data

**Comment by AlexanderPico** [comment]
I was concerned about how this site would scale given all the crosslinks we wanted (e.g., to/from pathways and each community/organism/ontology).  So, I wrote [a little R script](https://github.com/wikipathways/wikipathways.github.io/blob/main/generate-data.R) to dump simplified versions of all the approved pathways and their data that I could access from via web services.  @mkutmon: though oversimplified, this may be helpful in developing your more complete solution.

Good news: With 1842 pathways loaded and most of the crosslinks we want, the Jekyll site is build in ~35 seconds, and then (as a static site) is blazing fast for visitors.

For local testing, you can most most of the files in _pathways to a temp subfolder so that the site can be rebuilt in under a second.

**Comment by mkutmon** [comment]
Very cool! This is great! I'm focussing on checking the GitHub API first but this is next on my list!

**Comment by AlexanderPico** [comment]
Added all ontology tags and structured SEO data to all pathways. Site takes ~2 minutes to build now.

Things missing:
- authors -- use GPML and GitHub authors? (see WP554.md for example)
- tables -- for participants, interactions and references (see _data)
- seo keywords -- extract textLabels for all DataNodes and Labels form GPML? (see WP554.md for example)
- viewer support for other organisms (see https://github.com/wikipathways/GPML-Repo/issues/12)

**Comment by AlexanderPico** [comment]
@egonw Any feedback on my attempts so far to add structured metadata to our new site's pathway pages?

https://search.google.com/test/rich-results?id=isqypwnAjETrru-BxCMziA 
(click to expand on Dataset entry)

**Comment by mkutmon** [comment]
does the whole page need to rebuild every time a pathway is added?

**Comment by egonw** [comment]
> does the whole page need to rebuild every time a pathway is added?

that can be automated

**Comment by egonw** [comment]
> @egonw Any feedback on my attempts so far to add structured metadata to our new site's pathway pages?

I started to reboot the process of creating a `Pathway` or `BiologicalProcess` profile.

**Comment by mkutmon** [comment]
> > does the whole page need to rebuild every time a pathway is added?
> 
> that can be automated

Yes but is the page then not accessible in the 2 min it needs to rebuild?

**Comment by egonw** [comment]
> Yes but is the page then not accessible in the 2 min it needs to rebuild?

My impression so far is that the old page is replaced instantaneously. There is a delay between the commit push, as the building takes time, but during the building, the old page remains visible.

**Comment by AlexanderPico** [comment]
Latest features for new website:
- Gallery and list tabs on [community](https://new.wikipathways.org/communities/covid19.html), annotation, organism and browse pages.
- [Filterable table](https://new.wikipathways.org/pathways.html)
- [Faceted search](https://new.wikipathways.org/pathways_filters.html?org=Homo%20sapiens&com=COVID19)
- Lots of [badges, buttons and tools](https://new.wikipathways.org/pathways/WP554.html)
